### ISSUE TITLE
need modified for  setup.sh 

### ISSUE THREAD

**Issue by liesun1994** [tempra28/tree2seq#3]
1. git clone git@github.com:hassyGo/N3LP.git    need to modified to 
    git clone https://github.com/hassyGo/N3LP.git
2.  cp LSTM.* TreeLSTM.* BlackOut.* SoftMax.* Vocabulary.*  ..   need modified to 
    cp LSTM.* TreeLSTM.* BlackOut.* SoftMax.* Vocabulary.* Optimizer.*  .. 
   here you omitted Optimizer.*  into your tree2seq code

**Comment by akikoe** [comment]
Hi liesun1994,
Thank you for your issue! I've revised setup.sh.
